#!/bin/env python3

# https://learn.sparkfun.com/tutorials/setting-up-a-raspberry-pi-3-as-an-access-point/all
# https://www.baeldung.com/linux/wifi-display-realtime-info
# https://hawksites.newpaltz.edu/myerse/2018/06/08/hostapd-on-raspberry-pi/
# https://maker.pro/raspberry-pi/tutorial/connecting-raspberry-pi-3-wi-fi-via-bluetooth

import pdb
import re
import socket
import subprocess


def enable_hostapd(hostname,adapter,essid):
    # Hostapd Config
    config = f'''# Generated by enable_hostapd
interface={adapter.decode()}
driver=nl80211
ssid={hostname.decode()}
channel=4
hw_mode=b
macaddr_acl=0
auth_algs=3
ignore_broadcast_ssid=0
'''
    open('/etc/hostapd/hostapd.conf','wb').write(config.encode())
    subprocess.run(f'ifconfig {adapter.decode()} down'.split())
    subprocess.run('systemctl unmask hostapd.service'.split())
    subprocess.run('systemctl start hostapd.service'.split())




def net_info():
    hostname=socket.gethostname().encode()
    try:
        ad = subprocess.run(b'cat /proc/net/wireless'.split(), capture_output = True)
        ad = ad.stdout.split(b'\n')[2].strip().split()[0][:-1]
    except:
        return (hostname,'None','None',)
        
    try:
        iwconfig = subprocess.run(['iwconfig',ad], capture_output = True)
        essid = iwconfig.stdout.split(b'\n')[0].strip()
        essid = re.search(b'ESSID:"([^"]*)"',essid).group(1)
    except:
        return (hostname,ad,'None')

    return (hostname,ad,essid)

def main():
    (hostname,adapter,essid) = net_info()
    enable_hostapd(hostname,adapter,essid)

main()
