#!/bin/bash

SOURCE=/p/vproj/import/fm128a
DEST=/p/vproj/scans/fm128

if [[ -d "${DEST}"} ]]; then
    let diri=1
else    
    let diri=$(ls ${DEST}/??? | sort)
fi
let diri=1

echo diri $diri

if [[ -d "${DEST}/$(printf '%03u' ${diri})" ]]; then
    let destcount=$(ls ${DEST}/$(printf "%03u" $diri)/rawfile/*.raw | sort | head -1)
else
    let destcount=0
fi

let filecount=0

echo destcount $destcount filecount $filecount
exit 0

mkdir -p ${DEST}/001/rawfile

for ff in $( ls ${SOURCE}/*.raw | sort); do
    cp ${ff} ${DEST}/$(printf "%03u" ${diri})/rawfile/$(printf "%06ua.raw" ${destcount})

    ((filecount++))
    ((destcount++))
    if ((destcount == 1000)); then
        ((diri++))
        let destcount=0
        mkdir -p ${DEST}/$(printf "%03u" ${diri})/rawfile
    fi
done
